# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('headliner', models.CharField(max_length=255)),
                ('openers', jsonfield.fields.JSONField()),
                ('showtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='show_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_api.ShowVenue'),
        ),
    ]
