# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='openers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
