# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_api', '0003_auto_20171119_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set([('show_venue', 'headliner', 'showtime')]),
        ),
    ]
